version: "3.7"
services:
  www:
    build: .
    ports:
      - 8101:80
    volumes:
      - ./www:/var/www/html/
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
    networks:
      - default
    restart: always

  # Diesen Block auskommentieren, um phpmyadmin nicht zu nutzen
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8100:80
    links:
      - db:db
    restart: always

  db:
    image: mysql
    ports:
      - 3310:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8',
        '--collation-server=utf8_general_ci'
      ]
    volumes:
      - ./mysql_data:/var/lib/mysql
      # automatisches Importieren von allen Dumps in `dumps`
      - ./dumps/:/docker-entrypoint-initdb.d
    networks:
      - default
